مساله:

**فروش به تفکیک سال و فصل**

**به صورت ماترسی**

روش چهارم:

Sub Query + JOIN

In [ ]:
SELECT 
	Y.OrderYear,
	Q1.Sales AS Q1_Sales,
	Q2.Sales AS Q2_Sales,
	Q3.Sales AS Q3_Sales,
	Q4.Sales AS Q4_Sales
FROM 
	(
		SELECT 
			YEAR(SOH.OrderDate)					AS OrderYear
		FROM
			Sales.SalesOrderHeader AS SOH 
		GROUP BY
			YEAR(SOH.OrderDate)
	) AS Y
LEFT OUTER JOIN
	(
		SELECT 
			YEAR(SOH.OrderDate)					AS OrderYear,
			SUM(SOD.OrderQty * SOD.UnitPrice)	AS Sales
		FROM
			Sales.SalesOrderHeader AS SOH --31,465
		INNER JOIN
			Sales.SalesOrderDetail AS SOD --121,317
		ON
			SOH.SalesOrderID = SOD.SalesOrderID
		WHERE
			DATEPART(QUARTER, SOH.OrderDate) = 1
		GROUP BY
			YEAR(SOH.OrderDate)
	) AS Q1
ON
	Y.OrderYear = Q1.OrderYear
LEFT OUTER JOIN
	(
		SELECT 
			YEAR(SOH.OrderDate)					AS OrderYear,
			SUM(SOD.OrderQty * SOD.UnitPrice)	AS Sales
		FROM
			Sales.SalesOrderHeader AS SOH --31,465
		INNER JOIN
			Sales.SalesOrderDetail AS SOD --121,317
		ON
			SOH.SalesOrderID = SOD.SalesOrderID
		WHERE
			DATEPART(QUARTER, SOH.OrderDate) = 2
		GROUP BY
			YEAR(SOH.OrderDate)
	
	) AS Q2
ON
	Y.OrderYear = Q2.OrderYear
LEFT OUTER JOIN
	(
		SELECT 
			YEAR(SOH.OrderDate)					AS OrderYear,
			SUM(SOD.OrderQty * SOD.UnitPrice)	AS Sales
		FROM
			Sales.SalesOrderHeader AS SOH --31,465
		INNER JOIN
			Sales.SalesOrderDetail AS SOD --121,317
		ON
			SOH.SalesOrderID = SOD.SalesOrderID
		WHERE
			DATEPART(QUARTER, SOH.OrderDate) = 3
		GROUP BY
			YEAR(SOH.OrderDate)
		
	) AS Q3
ON
	Y.OrderYear = Q3.OrderYear
LEFT OUTER JOIN
	(
		SELECT 
			YEAR(SOH.OrderDate)					AS OrderYear,
			SUM(SOD.OrderQty * SOD.UnitPrice)	AS Sales
		FROM
			Sales.SalesOrderHeader AS SOH --31,465
		INNER JOIN
			Sales.SalesOrderDetail AS SOD --121,317
		ON
			SOH.SalesOrderID = SOD.SalesOrderID
		WHERE
			DATEPART(QUARTER, SOH.OrderDate) = 4
		GROUP BY
			YEAR(SOH.OrderDate)
	) AS Q4
ON
	Y.OrderYear = Q4.OrderYear
ORDER BY
	Y.OrderYear